### ISSUE TITLE
Disappearing Tested data for US States?

### ISSUE THREAD

**Issue by webstergl** [lazd/coronadatascraper#401] opened 2020-03-26 21:39 UTC
Hello,

I am a math teacher and super unfamiliar with this site and github, but I stumbled across as a resource for a stats project for my students. The data looks to have changed a lot from yesterday in the "Tested" column for US states. Yesterday there was testing data for all by 7 states. But today most of those cells are blanks. Just curious if that is an error and if that data will return.

Thank you, these is an amazing resource!

Gabe

**Comment by zbraniecki** [comment] 2020-03-26 21:44
Dupe of #386?

**Comment by lazd** [comment] 2020-03-27 00:17
@webstergl yup, we're no longer using COVID Tracking as authoritative for state data, our scrapers directly from that state override it. Unless the state provides testing numbers, it won't show up. Please pile on #386 and see if you can help identify states that provide testing information we can scrape.

**Closed by lazd** 2020-03-27 00:17 UTC
