### ISSUE TITLE
Scraper for DEU (Germany) regions

### ISSUE THREAD

**Issue by lazd** [lazd/coronadatascraper#79] opened 2020-03-16 08:55 UTC
We need regional data for DEU.

**Comment by hyperknot** [comment] 2020-03-16 17:02
datawrapper.de writes in: https://blog.datawrapper.de/coronaviruscharts/#considerations

<p>For the <a href="#map-germany">state map of Germany</a>, we use numbers from the <a href="https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Fallzahlen.html" target="_blank" rel="noopener"><strong>Robert Koch Insitute</strong></a>. This source is official, but updated slowly in comparison to e.g. this <a href="https://www.zeit.de/wissen/gesundheit/2020-03/coronavirus-deutschland-infektionen-faelle-verbreitung-epidemie-karte" target="_blank" rel="noopener">map by ZEIT Online</a>. The exact German locations of coronavirus cases came from <strong>René Engmann and his website <a href="https://www.coronavirus.jetzt/" target="_blank" rel="noopener">coronavirus.jetzt</a>.</strong> He and his team collected the data <a href="https://github.com/iceweasel1/COVID-19-Germany" target="_blank" rel="noopener">in this Github repo.</a> and were amazingly quick at updating the data about Germany until they stopped doing so on March 11th. We still left the out-dated maps in here.</p>

**Comment by jgehrcke** [comment] 2020-03-17 11:08
I also found that zeit.de is right now the best source in Germany. I think they collaborate with individual state ministries and therefore the numbers are pretty official. They are however much more real-time than the numbers published by Robert Koch Institute (the RKI needs about a day before they process and publish).

**Comment by jgehrcke** [comment] 2020-03-17 14:14
I am going to help with that @lazd -- my email address is jgehrcke@googlemail.com

**Comment by jgehrcke** [comment] 2020-03-17 17:18
Unfortunately I could not reach the people behind https://www.coronavirus.jetzt/. Right now zeit.de provides a larger count than coronavirus.jetzt. Given that zeit.de is one of the largest newspapers in Germany (of quality) I will proceed under the assumption that zeit.de is one of the best data sources to bet on for the coming hours, days, and weeks.

**Comment by jgehrcke** [comment] 2020-03-17 20:06
Here we go:

```
$ curl https://covid19-germany.appspot.com/now 2> /dev/null| jq
{
  "last_update_from_source_iso8601": "2020-03-17T20:03:41+00:00",
  "source": "zeit.de",
  "total_cases_confirmed_until_now": 9293
}
```

I did build https://covid19-germany.appspot.com/now  and plan to maintain it. Goal: data quality, and data freshness. Right now the source is, as argued above, zeit.de.

**Comment by hyperknot** [comment] 2020-03-18 23:03
@jgehrcke can you get their county level data? As is visible on this page: https://www.coronavirus.jetzt/karten/deutschland/

**Comment by jgehrcke** [comment] 2020-03-18 23:08
@hyperknot I am working on that. There is no official credible non-PDF data source for county level.

The data you have linked is out of date.

Germany's data processing is stone-age, this needs to be done by volunteers in a structured fashion. I am on that, and I will expose time-resolved county-level data via https://covid19-germany.appspot.com, too. 

Until then the country-level is good enough, isn't it?

**Comment by hyperknot** [comment] 2020-03-18 23:58
@jgehrcke of course, that a lot for the effort! I didn't think it'd be so difficult.

**Comment by jgehrcke** [comment] 2020-03-19 04:15
Announcing the API that provides time series data for individual German states: https://gehrcke.de/2020/03/covid-19-http-api-german-states-timeseries/

**Comment by Wikunia** [comment] 2020-03-20 12:48
Data per county is available here https://npgeo-corona-npgeo-de.hub.arcgis.com/datasets/917fc37a709542548cc3be077a786c17_0

**Comment by Wikunia** [comment] 2020-03-20 12:52
This data is only a snapshot of the current state so don't know how to create a timeseries for it

**Comment by hyperknot** [comment] 2020-03-20 12:53
All our sources are only snapshot, the scraper takes care of saving previous history.

**Comment by Wikunia** [comment] 2020-03-20 13:04
As there is a scraper for DEU already what is the best way to add this? Adding another folder in scrapers?

**Comment by hyperknot** [comment] 2020-03-20 13:09
I don't know, we should ask @lazd about that.

**Comment by Wikunia** [comment] 2020-03-20 15:09
Hi @jgehrcke yes I just found the data and created a scraper out of it without thinking too much about it :smile: 
I think this community effort is awesome but it creates overlapping things like this where one can't precisely define which one is better. 
Maybe some people want the rki data as a reliable source which lags behind a bit but in a few weeks this doesn't matter anymore. The county level might be interesting for some but the general international public probably doesn't care. It would be nice to be able to have all datasets in but maybe have an api where such criteria can be mentioned. 
Maybe @lazd has some comments about it.

**Comment by jgehrcke** [comment] 2020-03-20 22:59
Okay, thanks @Wikunia. 

If in a couple of weeks it turns out that as of certain developments we'd like to switch the data source then we can certainly do this. I am not married to maintaining a data set :D, there are nicer things in life. However, focusing on the next days, though, for keeping the momentum (and supporting the momentum with _quality_ data!), let's keep using the fresher data as published by the individual Gesundheitsministerien. Is that okay with you? Also, of course, in terms of willingness and also ability to curate things for now I'd prefer to continue using https://github.com/jgehrcke/covid-19-germany-gae.

**Comment by dadosch** [comment] 2020-03-22 17:25
Please see https://github.com/corona-zahlen-landkreis/corona_landkreis_fallzahlen_scraping/tree/master/landkreise/data
We scrape county's website to have a more up to date data per county or in finer levels. The identifier is the official identifier https://de.wikipedia.org/wiki/Amtlicher_Gemeindeschl%C3%BCssel

**Comment by martiL** [comment] 2020-03-23 10:42
@lazd Is there are a data scraper for german regions? I see open pull request but I don't see it in the data

**Comment by jgehrcke** [comment] 2020-03-23 14:56
> @lazd Is there are a data scraper for german regions? I see open pull request but I don't see it in the data

Should be a matter of hours now. We iterated on the implementation quite a bit.  https://github.com/lazd/coronadatascraper/pull/196

**Comment by martiL** [comment] 2020-03-23 16:58
> > @lazd Is there are a data scraper for german regions? I see open pull request but I don't see it in the data
> 
> Should be a matter of hours now. We iterated on the implementation quite a bit. #196
> 
> Edit: merged! 🚀

@jgehrcke 
I am so grateful for everything you do! We are trying to create a landing page and API to make it easier for people to consume and contribute data to this amazing project :-)

https://corona-api-landingpage.netlify.com/

**Comment by martiL** [comment] 2020-03-24 13:14
<img width="1353" alt="Bildschirmfoto 2020-03-24 um 14 11 31" src="https://user-images.githubusercontent.com/5569498/77429185-8ed6e400-6dd9-11ea-9427-1317d40aa999.png">

@jgehrcke @lazd There seems to be wrong coordinates for the German region BB... you can reproduce it here -> https://corona-api-dashboard.netlify.com/

**Comment by jgehrcke** [comment] 2020-03-24 13:19
@martiL woof! I tried to double-check things and already knew that _this_ is probably the most error-prone part :-) Fix here: https://github.com/lazd/coronadatascraper/pull/304

**Comment by jgehrcke** [comment] 2020-03-24 15:27
@lazd @qgolsteyn I think we should close this issue for now, and create more fine-grained issues from here as they come up!

**Comment by qgolsteyn** [comment] 2020-03-24 18:56
Sounds good!

**Closed by qgolsteyn** 2020-03-24 18:56 UTC
Labels: critical, help wanted
