### ISSUE TITLE
Add older data from CSSEGISandData/COVID-19 

### ISSUE THREAD

**Issue by ch3ft0ny** [lazd/coronadatascraper#377] opened 2020-03-26 08:02 UTC
Hello,

great project, but for some countries the timeline data starts really late.
e.g. the data for Italy starts from 2020-02-24, the first reported case was 2020-01-31.

Its not a big issue, but it would be really nice

**Comment by lazd** [comment] 2020-03-26 14:44
Duplicate of #375 (fixing now!)

**Closed by lazd** 2020-03-26 14:44 UTC
