### ISSUE TITLE
replicated rows for USA total data

### ISSUE THREAD

**Issue by raysalem** [lazd/coronadatascraper#349] opened 2020-03-25 16:57 UTC
I am observing that at least for the US it is repeated twice
USA repeated twice with two country codes US and USA
test code in python --> 
`df = pd.read_csv("http://blog.lazd.net/coronadatascraper/data.csv",parse_dates=True)
df[(df["cases"]>1e4)&df["country"].str.contains("US")]`

Data base i am observing, with said code -->

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>city</th>\n      <th>county</th>\n      <th>state</th>\n      <th>country</th>\n      <th>cases</th>\n      <th>deaths</th>\n      <th>recovered</th>\n      <th>tested</th>\n      <th>active</th>\n      <th>population</th>\n      <th>lat</th>\n      <th>long</th>\n      <th>url</th>\n      <th>maintainers</th>\n      <th>rating</th>\n      <th>tz</th>\n      <th>featureId</th>\n      <th>sources</th>\n      <th>curators</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>199</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>US</td>\n      <td>53740.0</td>\n      <td>706.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>53034.0</td>\n      <td>326625791.0</td>\n      <td>45.119614</td>\n      <td>0.761872</td>\n      <td>https://github.com/CSSEGISandData/COVID-19</td>\n      <td>[{"name":"Larry Davis","email":"lazdnet@gmail....</td>\n      <td>0.414634</td>\n      <td>["Europe/Paris"]</td>\n      <td>192.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>375</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NY</td>\n      <td>USA</td>\n      <td>25665.0</td>\n      <td>210.0</td>\n      <td>NaN</td>\n      <td>91270.0</td>\n      <td>25455.0</td>\n      <td>19453561.0</td>\n      <td>42.760805</td>\n      <td>-75.840971</td>\n      <td>https://covidtracking.com/api/states</td>\n      <td>NaN</td>\n      <td>0.341463</td>\n      <td>["America/New_York"]</td>\n      <td>353.0</td>\n      <td>NaN</td>\n      <td>[{"name":"The COVID Tracking Project","url":"h...</td>\n    </tr>\n    <tr>\n      <th>396</th>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>USA</td>\n      <td>53192.0</td>\n      <td>709.0</td>\n      <td>NaN</td>\n      <td>367710.0</td>\n      <td>52483.0</td>\n      <td>326625791.0</td>\n      <td>45.119614</td>\n      <td>0.761872</td>\n      <td>https://covidtracking.com/api/states</td>\n      <td>NaN</td>\n      <td>0.341463</td>\n      <td>["Europe/Paris"]</td>\n      <td>192.0</td>\n      <td>NaN</td>\n      <td>[{"name":"The COVID Tracking Project","url":"h...</td>\n    </tr>\n    <tr>\n      <th>2513</th>\n      <td>New York City</td>\n      <td>NaN</td>\n      <td>NY</td>\n      <td>USA</td>\n      <td>14904.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>NaN</td>\n      <td>14904.0</td>\n      <td>8398748.0</td>\n      <td>40.706840</td>\n      <td>-73.978335</td>\n      <td>https://coronavirus.health.ny.gov/county-count...</td>\n      <td>NaN</td>\n      <td>0.463415</td>\n      <td>["America/New_York"]</td>\n      <td>2453.0</td>\n      <td>NaN</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>'

**Comment by cmcjacob** [comment] 2020-03-25 17:11
Seems covidtracking data is also aggregated for cross referencing / fallback purposes.  If you exclude that source does it address your problem?

**Comment by lazd** [comment] 2020-03-25 22:01
The US/USA issue is definitely a problem, I can address that.

Otherwise, we have New York City without a county, because the city contains counties, so that's working as designed.

**Comment by lazd** [comment] 2020-03-25 22:12
Just pushed a fix for this. Check again after 9PM PST tonight and re-open this issue if you still see duplicate USA/US entires.

**Closed** 2020-03-25 22:12 UTC
