### ISSUE TITLE
Missing data fro NY

### ISSUE THREAD

**Issue by ekaterinakuzmina** [lazd/coronadatascraper#347] opened 2020-03-25 15:14 UTC
Hy guys, yesterday data for NY from March 12 till March 22 disappeared.

**Comment by alexmill** [comment] 2020-03-25 21:28
Duplicate of https://github.com/lazd/coronadatascraper/issues/323

**Comment by lazd** [comment] 2020-03-25 22:32
Yes it does seem like this is a dupe. Closing, @ekaterinakuzmina please follow along in the other issue.

**Closed by lazd** 2020-03-25 22:32 UTC
